# Generated by Django 4.1.7 on 2023-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
